# Generated by Django 2.1.1 on 2018-10-17 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='summary',
        ),
        migrations.AddField(
            model_name='page',
            name='story',
            field=models.CharField(default=django.utils.timezone.now, help_text='Write your story.', max_length=1000),
            preserve_default=False,
        ),
    ]
