# Generated by Django 2.1.1 on 2018-11-24 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='story',
            field=models.TextField(help_text='Write your story.'),
        ),
    ]
