# Generated by Django 2.1.1 on 2018-11-05 18:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='picture',
            field=models.URLField(default=django.utils.timezone.now, help_text='Enter a valid URL', max_length=500),
            preserve_default=False,
        ),
    ]
