# Generated by Django 2.1.2 on 2018-11-28 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20181124_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
