# Generated by Django 2.1.1 on 2018-10-18 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_auto_20181017_1908'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='diary',
            name='last_name',
        ),
    ]
