# Generated by Django 2.1.1 on 2018-10-27 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0002_page_diary_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='diary_logo',
        ),
    ]
