# Generated by Django 2.1.1 on 2018-10-21 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0003_remove_diary_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diary',
            name='first_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
