# Generated by Django 2.1.1 on 2018-10-21 10:28

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0004_auto_20181021_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name=datetime.date(2018, 10, 21)),
            preserve_default=False,
        ),
    ]
