# Generated by Django 2.1.1 on 2018-10-22 08:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0005_page_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='date',
            field=models.DateField(verbose_name=datetime.date(2018, 10, 22)),
        ),
    ]
