# Generated by Django 2.1.1 on 2018-10-22 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0006_auto_20181022_1541'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
    ]
