# Generated by Django 2.1.1 on 2018-10-24 15:56

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('taggit', '0002_auto_20150616_2121'),
        ('diary', '0007_auto_20181022_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='tag',
        ),
        migrations.AddField(
            model_name='page',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
