# Generated by Django 2.1.1 on 2018-10-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0008_auto_20181024_2256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='tags',
        ),
        migrations.AddField(
            model_name='page',
            name='tag',
            field=models.ManyToManyField(help_text='Select a tag', related_name='Page', to='diary.Tag'),
        ),
    ]
