# Generated by Django 2.1.1 on 2018-10-24 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0009_auto_20181024_2311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='tag',
        ),
        migrations.AddField(
            model_name='page',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diary.Tag'),
        ),
    ]
